ユーザー辞書機能の追加
VOICEVOX/pyopenjtalk pull request #2
Opened 2021-12-16 17:30 UTC by takana-v

## 関連PR
- https://github.com/Hiroshiba/pyopenjtalk/pull/1
- https://github.com/VOICEVOX/voicevox_engine/pull/234

リポジトリの場所の移動があったため別でPRしています。

2021-12-16 17:40 UTC, Yosshi999 commented
これ僕のコミットなのでそのままapproveしちゃおうと思ったんですが、せっかくなので日本語の混じったファイル名だった場合にどうなるか調べてみてほしいです

2021-12-16 17:42 UTC, Hiroshiba requested changes
本家に送られているプルリクエストがこちらでしょうか。

- https://github.com/r9y9/pyopenjtalk/pull/26

できる限り、取り込まれるであろうプルリクエストと同じ形にしておくとメンテナンス性が上がりそうですが、そのままだとwindowsの日本語パスで動かなくなるので変更は必須になりそうでした。

その変更を @.takana-v にお願いするのはどこか違和感があるかもですが、修正頂けると幸いです･･･！

2021-12-16 17:42 UTC, Hiroshiba commented on pyopenjtalk/__init__.py
> +    CreateUserDict(OPEN_JTALK_DICT_DIR, path.encode("utf-8"), out_path.encode("utf-8"))
このままだとwindowsの日本語パスでエラーが出そうです。
VOICEVOXのmasterにあるこちらを使って頂けると！

https://github.com/VOICEVOX/pyopenjtalk/blob/8b3d7a64fa87f00d44b3a4802ee98fc7bf9c1099/pyopenjtalk/__init__.py#L25

2021-12-16 17:42 UTC, Hiroshiba commented on pyopenjtalk/__init__.py
> +        dn_mecab=OPEN_JTALK_DICT_DIR, user_mecab=path.encode("utf-8")
ここも同上そうです

2021-12-17 07:47 UTC, Yosshi999 commented
あれ、もしかしてこのブランチに書き込めるのって僕だけですか？

2021-12-17 10:42 UTC, takana-v commented
修正が必要になると考えずに直接 @Yosshi999  のブランチでPRしてましたね...申し訳ないです。
日本語パスではインタプリタごと落ちたので修正が必要そうです。
自分の方でブランチ作ってPRしなおそうかと考えているのですがどうでしょうか？
（もし既に作業中ならその旨を伝えていただければと思います）

2021-12-17 12:35 UTC, Yosshi999 commented
手を付けてないのでそちらで作り直していただきたいです

インタプリタごと落ちるのはヤバそうですね。pyopenjtalkが使っているmecabはassertionを全て無効化しているので、途中で致命的なエラーが起こってもそのまま突き進んでしまいクラッシュするようです。cythonに飛ぶ前に一度ファイルの存在確認をしているのもそれが理由だったりします。
今後予期しないエラーでアプリケーションごとクラッシュするのはよろしくないのでサブプロセスとして切り離すのも選択肢としてあると思います

2021-12-17 13:44 UTC, takana-v commented
PRしなおしたためcloseします。
お手数お掛けして申し訳ありません。
- #3

2021-12-17 13:44 UTC, closed without merging